---
title: "Econ Thesis Equation"
author: "Erick Cohen"
date: "3/12/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The equation below will highlight the spillover effects I want to account for in my hypothesis. After talking with Leah Brooks at the Tractenburg School of Public Policy, we produced the equation bellow. The dependent variable, ${ln(P_i)}$, is the natural log of the price. This is the main thing I want to focus on. I have my $\alpha$ intercept and a vector of property and zipcode related variables to hold constant in my hedonic model denoted by $\gamma Z$. Next, I have my term $\beta_1 (I_i) + \beta_2 (I_i,_b*A_b)$. This is used to denoted property $i$ within the BID. $I$ is set equal to 1 if property $i$ is inside the BID. $A_b$ is my dummy variable indicating whether the BID $b$ was established before or after the sale date of property $i$. $A_b$ is equal to 1 if the BID was established on or after the date of sale of the property.The remaining terms will be my buffers and my interaction terms. They consist of multiple 50 meter buffers. $\beta_3 (W_{50},_i,_b) + \beta_4 (W_{50},_i,_b * A_b)$ shows property $i$ within 50 meters of a BID. $W$ is a dummy variable that is equal to 1 if it is within that 50 meter buffer. This is repeated every 50 meters until 2500 meters. 

$$
{ln(P_i)} = \alpha + \gamma Z + \beta_1 (I_i) + \beta_2 (I_i,_b*A_b) + \beta_3 (W_{50},_i,_b) + \beta_4 (W_{50},_i,_b * A_b) +   \beta_5 (W_{51-100},_i,_b) + \beta_6 (W_{51-100},_i,_b*A_b) + \beta_7 (W_{101-150},_i,_b) + \beta_8 (W_{101-150},_i,_b*A_b) +...+ \beta_{99} (W_{2451-2500},_i,_b) + \beta_{100} (W_{1951-2000},_i,_b*A_b) + \epsilon_i 
$$

Results table 



$$
Show in New WindowClear OutputExpand/Collapse Output

% Table created by stargazer v.5.2.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu
% Date and time: Fri, Mar 15, 2019 - 15:08:25
\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & price\_log \\ 
\hline \\[-1.8ex] 
 HF\_BATHRM\_1 & 0.099$^{***}$ \\ 
  & (0.004) \\ 
  & \\ 
 HF\_BATHRM\_2 & 0.141$^{***}$ \\ 
  & (0.009) \\ 
  & \\ 
 ZIPCODE\_20002 & $-$0.111$^{***}$ \\ 
  & (0.011) \\ 
  & \\ 
 ZIPCODE\_20003 & $-$0.034$^{**}$ \\ 
  & (0.013) \\ 
  & \\ 
 ZIPCODE\_20005 & 0.028 \\ 
  & (0.047) \\ 
  & \\ 
 ZIPCODE\_20007 & 0.184$^{***}$ \\ 
  & (0.021) \\ 
  & \\ 
 ZIPCODE\_20008 & 0.359$^{***}$ \\ 
  & (0.024) \\ 
  & \\ 
 ZIPCODE\_20009 & 0.221$^{***}$ \\ 
  & (0.016) \\ 
  & \\ 
 ZIPCODE\_20010 & 0.127$^{***}$ \\ 
  & (0.014) \\ 
  & \\ 
 ZIPCODE\_20011 & $-$0.059$^{***}$ \\ 
  & (0.018) \\ 
  & \\ 
 ZIPCODE\_20012 & 0.019 \\ 
  & (0.021) \\ 
  & \\ 
 ZIPCODE\_20015 & 0.273$^{***}$ \\ 
  & (0.021) \\ 
  & \\ 
 ZIPCODE\_20016 & 0.316$^{***}$ \\ 
  & (0.023) \\ 
  & \\ 
 ZIPCODE\_20017 & 0.048$^{***}$ \\ 
  & (0.015) \\ 
  & \\ 
 ZIPCODE\_20018 & $-$0.043$^{***}$ \\ 
  & (0.015) \\ 
  & \\ 
 ZIPCODE\_20019 & $-$0.391$^{***}$ \\ 
  & (0.025) \\ 
  & \\ 
 ZIPCODE\_20020 & $-$0.205$^{***}$ \\ 
  & (0.027) \\ 
  & \\ 
 ZIPCODE\_20024 & $-$0.157$^{***}$ \\ 
  & (0.028) \\ 
  & \\ 
 ZIPCODE\_20032 & $-$0.185$^{***}$ \\ 
  & (0.030) \\ 
  & \\ 
 ZIPCODE\_20036 & 0.285$^{***}$ \\ 
  & (0.066) \\ 
  & \\ 
 ZIPCODE\_20037 & 0.263$^{***}$ \\ 
  & (0.037) \\ 
  & \\ 
 ZIPCODE\_20052 & 0.623$^{***}$ \\ 
  & (0.155) \\ 
  & \\ 
 WARD\_Ward.1 & 0.343$^{***}$ \\ 
  & (0.030) \\ 
  & \\ 
 WARD\_Ward.2 & 0.500$^{***}$ \\ 
  & (0.033) \\ 
  & \\ 
 WARD\_Ward.3 & 0.582$^{***}$ \\ 
  & (0.033) \\ 
  & \\ 
 WARD\_Ward.4 & 0.497$^{***}$ \\ 
  & (0.031) \\ 
  & \\ 
 WARD\_Ward.5 & 0.300$^{***}$ \\ 
  & (0.027) \\ 
  & \\ 
 WARD\_Ward.6 & 0.505$^{***}$ \\ 
  & (0.027) \\ 
  & \\ 
 WARD\_Ward.7 & 0.316$^{***}$ \\ 
  & (0.015) \\ 
  & \\ 
 WARD\_Ward.8 &  \\ 
  &  \\ 
  & \\ 
 GRADE\_Above.Average & $-$0.172$^{***}$ \\ 
  & (0.009) \\ 
  & \\ 
 GRADE\_Average & $-$0.292$^{***}$ \\ 
  & (0.010) \\ 
  & \\ 
 GRADE\_Excellent & 0.056$^{***}$ \\ 
  & (0.016) \\ 
  & \\ 
 GRADE\_Exceptional.A & 0.230$^{***}$ \\ 
  & (0.045) \\ 
  & \\ 
 GRADE\_Exceptional.B & 0.162 \\ 
  & (0.144) \\ 
  & \\ 
 GRADE\_Exceptional.C & $-$0.562$^{**}$ \\ 
  & (0.235) \\ 
  & \\ 
 GRADE\_Fair.Quality & $-$0.472$^{***}$ \\ 
  & (0.046) \\ 
  & \\ 
 GRADE\_Good.Quality & $-$0.068$^{***}$ \\ 
  & (0.008) \\ 
  & \\ 
 GRADE\_Low.Quality & $-$0.426$^{*}$ \\ 
  & (0.238) \\ 
  & \\ 
 GRADE\_Superior & 0.087$^{***}$ \\ 
  & (0.019) \\ 
  & \\ 
 GRADE\_Very.Good &  \\ 
  &  \\ 
  & \\ 
 V54 & 0.105$^{***}$ \\ 
  & (0.022) \\ 
  & \\ 
 V55 & 0.057$^{**}$ \\ 
  & (0.022) \\ 
  & \\ 
 V56 & 0.091$^{***}$ \\ 
  & (0.024) \\ 
  & \\ 
 V57 & 0.143$^{***}$ \\ 
  & (0.025) \\ 
  & \\ 
 V58 & 0.141$^{***}$ \\ 
  & (0.025) \\ 
  & \\ 
 V59 & 0.133$^{***}$ \\ 
  & (0.027) \\ 
  & \\ 
 V60 & 0.069$^{**}$ \\ 
  & (0.030) \\ 
  & \\ 
 V61 & 0.122$^{***}$ \\ 
  & (0.029) \\ 
  & \\ 
 V62 & 0.110$^{***}$ \\ 
  & (0.030) \\ 
  & \\ 
 V63 & 0.039 \\ 
  & (0.029) \\ 
  & \\ 
 V64 & 0.034 \\ 
  & (0.030) \\ 
  & \\ 
 V65 & 0.018 \\ 
  & (0.028) \\ 
  & \\ 
 V66 & 0.005 \\ 
  & (0.028) \\ 
  & \\ 
 V67 & $-$0.036 \\ 
  & (0.029) \\ 
  & \\ 
 V68 & $-$0.012 \\ 
  & (0.031) \\ 
  & \\ 
 V69 & 0.010 \\ 
  & (0.029) \\ 
  & \\ 
 V70 & 0.017 \\ 
  & (0.028) \\ 
  & \\ 
 V71 & $-$0.006 \\ 
  & (0.026) \\ 
  & \\ 
 V72 & $-$0.104$^{***}$ \\ 
  & (0.026) \\ 
  & \\ 
 V73 & $-$0.066$^{**}$ \\ 
  & (0.028) \\ 
  & \\ 
 V74 & 0.017 \\ 
  & (0.027) \\ 
  & \\ 
 V75 & $-$0.046 \\ 
  & (0.030) \\ 
  & \\ 
 V76 & $-$0.031 \\ 
  & (0.029) \\ 
  & \\ 
 V77 & 0.021 \\ 
  & (0.027) \\ 
  & \\ 
 V78 & 0.037 \\ 
  & (0.032) \\ 
  & \\ 
 V79 & 0.065$^{**}$ \\ 
  & (0.030) \\ 
  & \\ 
 V80 & $-$0.075$^{**}$ \\ 
  & (0.030) \\ 
  & \\ 
 V81 & $-$0.021 \\ 
  & (0.033) \\ 
  & \\ 
 V82 & $-$0.002 \\ 
  & (0.032) \\ 
  & \\ 
 V83 & 0.058$^{***}$ \\ 
  & (0.019) \\ 
  & \\ 
 V84 & 0.026 \\ 
  & (0.035) \\ 
  & \\ 
 V85 & 0.045 \\ 
  & (0.036) \\ 
  & \\ 
 V86 & $-$0.023 \\ 
  & (0.035) \\ 
  & \\ 
 V87 & $-$0.030 \\ 
  & (0.033) \\ 
  & \\ 
 V88 & $-$0.045 \\ 
  & (0.032) \\ 
  & \\ 
 V89 & $-$0.013 \\ 
  & (0.033) \\ 
  & \\ 
 V90 & $-$0.085$^{***}$ \\ 
  & (0.033) \\ 
  & \\ 
 V91 & 0.003 \\ 
  & (0.035) \\ 
  & \\ 
 V92 & $-$0.013 \\ 
  & (0.034) \\ 
  & \\ 
 V93 & 0.012 \\ 
  & (0.038) \\ 
  & \\ 
 V94 & 0.050 \\ 
  & (0.034) \\ 
  & \\ 
 V95 & 0.035 \\ 
  & (0.033) \\ 
  & \\ 
 V96 & 0.099$^{***}$ \\ 
  & (0.032) \\ 
  & \\ 
 V97 & 0.007 \\ 
  & (0.036) \\ 
  & \\ 
 V98 & 0.002 \\ 
  & (0.039) \\ 
  & \\ 
 V99 & $-$0.005 \\ 
  & (0.039) \\ 
  & \\ 
 V100 & 0.054 \\ 
  & (0.037) \\ 
  & \\ 
 V101 & 0.068$^{*}$ \\ 
  & (0.038) \\ 
  & \\ 
 V102 & 0.086$^{**}$ \\ 
  & (0.038) \\ 
  & \\ 
 V103 & $-$0.006 \\ 
  & (0.041) \\ 
  & \\ 
 CNDTN\_Average & $-$0.260$^{***}$ \\ 
  & (0.007) \\ 
  & \\ 
 CNDTN\_Default & $-$0.364 \\ 
  & (0.406) \\ 
  & \\ 
 CNDTN\_Excellent & $-$0.035$^{**}$ \\ 
  & (0.018) \\ 
  & \\ 
 CNDTN\_Fair & $-$0.374$^{***}$ \\ 
  & (0.020) \\ 
  & \\ 
 CNDTN\_Good & $-$0.085$^{***}$ \\ 
  & (0.007) \\ 
  & \\ 
 CNDTN\_Poor & $-$0.541$^{***}$ \\ 
  & (0.045) \\ 
  & \\ 
 CNDTN\_Very.Good &  \\ 
  &  \\ 
  & \\ 
 V111 & 0.219$^{***}$ \\ 
  & (0.025) \\ 
  & \\ 
 V112 & 0.266$^{***}$ \\ 
  & (0.025) \\ 
  & \\ 
 V113 & 0.238$^{***}$ \\ 
  & (0.027) \\ 
  & \\ 
 V114 & 0.154$^{***}$ \\ 
  & (0.030) \\ 
  & \\ 
 V115 & 0.179$^{***}$ \\ 
  & (0.029) \\ 
  & \\ 
 V116 & 0.199$^{***}$ \\ 
  & (0.031) \\ 
  & \\ 
 V117 & 0.186$^{***}$ \\ 
  & (0.035) \\ 
  & \\ 
 V118 & 0.181$^{***}$ \\ 
  & (0.034) \\ 
  & \\ 
 V119 & 0.164$^{***}$ \\ 
  & (0.035) \\ 
  & \\ 
 V120 & 0.250$^{***}$ \\ 
  & (0.034) \\ 
  & \\ 
 V121 & 0.213$^{***}$ \\ 
  & (0.034) \\ 
  & \\ 
 V122 & 0.232$^{***}$ \\ 
  & (0.033) \\ 
  & \\ 
 V123 & 0.260$^{***}$ \\ 
  & (0.033) \\ 
  & \\ 
 V124 & 0.300$^{***}$ \\ 
  & (0.033) \\ 
  & \\ 
 V125 & 0.269$^{***}$ \\ 
  & (0.037) \\ 
  & \\ 
 V126 & 0.209$^{***}$ \\ 
  & (0.034) \\ 
  & \\ 
 V127 & 0.263$^{***}$ \\ 
  & (0.033) \\ 
  & \\ 
 V128 & 0.268$^{***}$ \\ 
  & (0.031) \\ 
  & \\ 
 V129 & 0.326$^{***}$ \\ 
  & (0.031) \\ 
  & \\ 
 V130 & 0.274$^{***}$ \\ 
  & (0.031) \\ 
  & \\ 
 V131 & 0.208$^{***}$ \\ 
  & (0.031) \\ 
  & \\ 
 V132 & 0.191$^{***}$ \\ 
  & (0.035) \\ 
  & \\ 
 V133 & 0.220$^{***}$ \\ 
  & (0.035) \\ 
  & \\ 
 V134 & 0.162$^{***}$ \\ 
  & (0.033) \\ 
  & \\ 
 V135 & 0.094$^{**}$ \\ 
  & (0.039) \\ 
  & \\ 
 V136 & 0.049 \\ 
  & (0.037) \\ 
  & \\ 
 V137 & 0.167$^{***}$ \\ 
  & (0.037) \\ 
  & \\ 
 V138 & 0.107$^{***}$ \\ 
  & (0.040) \\ 
  & \\ 
 V139 & 0.095$^{**}$ \\ 
  & (0.040) \\ 
  & \\ 
 V140 & 0.055 \\ 
  & (0.042) \\ 
  & \\ 
 V141 &  \\ 
  &  \\ 
  & \\ 
 V142 & 0.028 \\ 
  & (0.043) \\ 
  & \\ 
 V143 & 0.163$^{***}$ \\ 
  & (0.044) \\ 
  & \\ 
 V144 & 0.129$^{***}$ \\ 
  & (0.043) \\ 
  & \\ 
 V145 & 0.093$^{**}$ \\ 
  & (0.041) \\ 
  & \\ 
 V146 & 0.050 \\ 
  & (0.041) \\ 
  & \\ 
 V147 & 0.115$^{***}$ \\ 
  & (0.041) \\ 
  & \\ 
 V148 & 0.008 \\ 
  & (0.043) \\ 
  & \\ 
 V149 & 0.090$^{**}$ \\ 
  & (0.043) \\ 
  & \\ 
 V150 & 0.025 \\ 
  & (0.047) \\ 
  & \\ 
 V151 & 0.050 \\ 
  & (0.042) \\ 
  & \\ 
 V152 & 0.071$^{*}$ \\ 
  & (0.042) \\ 
  & \\ 
 V153 & 0.001 \\ 
  & (0.043) \\ 
  & \\ 
 V154 & 0.067 \\ 
  & (0.048) \\ 
  & \\ 
 V155 & 0.031 \\ 
  & (0.050) \\ 
  & \\ 
 V156 & 0.072 \\ 
  & (0.050) \\ 
  & \\ 
 V157 & 0.011 \\ 
  & (0.048) \\ 
  & \\ 
 V158 & $-$0.004 \\ 
  & (0.049) \\ 
  & \\ 
 V159 & 0.004 \\ 
  & (0.049) \\ 
  & \\ 
 V160 & 0.141$^{***}$ \\ 
  & (0.051) \\ 
  & \\ 
 BATHRM\_var & 0.088$^{***}$ \\ 
  & (0.003) \\ 
  & \\ 
 ROOMS\_var & 0.009$^{***}$ \\ 
  & (0.001) \\ 
  & \\ 
 BEDRM\_var & 0.026$^{***}$ \\ 
  & (0.002) \\ 
  & \\ 
 STORIES\_var & $-$0.0001 \\ 
  & (0.0005) \\ 
  & \\ 
 KITCHENS\_var & $-$0.034$^{***}$ \\ 
  & (0.004) \\ 
  & \\ 
 FIREPLACES\_var & 0.089$^{***}$ \\ 
  & (0.003) \\ 
  & \\ 
 sale\_date\_l\_var & 0.000$^{***}$ \\ 
  & (0.000) \\ 
  & \\ 
 squarefoot\_inBID\_var & 0.030$^{***}$ \\ 
  & (0.004) \\ 
  & \\ 
 after\_des\_var & $-$0.017$^{**}$ \\ 
  & (0.008) \\ 
  & \\ 
 after\_InBID\_designated\_var & 0.071$^{**}$ \\ 
  & (0.029) \\ 
  & \\ 
 Constant & 10.162$^{***}$ \\ 
  & (0.036) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 52,945 \\ 
R$^{2}$ & 0.721 \\ 
Adjusted R$^{2}$ & 0.720 \\ 
Residual Std. Error & 0.405 (df = 52790) \\ 
F Statistic & 886.542$^{***}$ (df = 154; 52790) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table} 
  
$$
```